# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e15a23b3395be04e11445637971774ade19de023ea6db6a5dfdb69a99a7a38b80334a300ec3e01adcb5e24b375b9d4a63bd6da5c08ee4b9e77f65a48b1ff5e74

test:
  secret_key_base: 635c146990c1007fa9842bf4291ccf211ef251c0d8edc9d4659e1a05a39759ddc49bedd5837ec1d41404e758242229ba6262e1ae24f33b0fc97727a0f78337a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
